USE canvas;

LOAD DATA LOCAL INFILE 'course.csv' INTO TABLE course
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'person.csv' INTO TABLE person
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'class.csv' INTO TABLE class
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'ta.csv' INTO TABLE ta
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'take.csv' INTO TABLE take
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'assignment.csv' INTO TABLE assignment
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'grade.csv' INTO TABLE grade
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'question.csv' INTO TABLE question
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'reply.csv' INTO TABLE reply
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'tag.csv' INTO TABLE tag
FIELDS TERMINATED BY ',' IGNORE 1 LINES;

LOAD DATA LOCAL INFILE 'hastag.csv' INTO TABLE hastag
FIELDS TERMINATED BY ',' IGNORE 1 LINES;